### ISSUE TITLE
无法正确处理带有Emoji的markdown文件

### ISSUE THREAD

**Issue by yurhett** [zweix123/jyyslide-md#9]
macOS 在处理example/jyy的文件时，报：
```
(jyyslide-md) jyyslide-md % python main.py ./example/jyy/操作系统概述.md
Traceback (most recent call last):
  File "~/anaconda3/envs/jyyslide-md/lib/python3.10/site-packages/pyquery/pyquery.py", line 59, in fromstring
    result = getattr(etree, meth)(context)
  File "src/lxml/etree.pyx", line 3257, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1916, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1796, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1085, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 618, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 728, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 657, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Char 0x0 out of allowed range, line 1, column 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/MyGit/jyyslide-md/main.py", line 9, in <module>
    converter(args.filepath)
  File "~/MyGit/jyyslide-md/src/converter.py", line 192, in converter
    st.body = get_body(st.content)
  File "~/MyGit/jyyslide-md/src/converter.py", line 127, in get_body
    html_first_sections = md_divide_to_horizontal(content)
  File "~/MyGit/jyyslide-md/src/converter.py", line 118, in md_divide_to_horizontal
    html_second_sections = horizontal_to_vertical(horizontal)
  File "~/MyGit/jyyslide-md/src/converter.py", line 102, in horizontal_to_vertical
    process_terminal(md_util.md_to_html(vertical_divided_by_second))
  File "~/MyGit/jyyslide-md/src/converter.py", line 41, in process_terminal
    semi_html = process_html_elements(temp)
  File "~/MyGit/jyyslide-md/src/converter.py", line 12, in process_html_elements
    page = pq(temp_html.strip())
  File "~/anaconda3/envs/jyyslide-md/lib/python3.10/site-packages/pyquery/pyquery.py", line 212, in __init__
    elements = fromstring(context, self.parser)
  File "~/anaconda3/envs/jyyslide-md/lib/python3.10/site-packages/pyquery/pyquery.py", line 63, in fromstring
    result = getattr(lxml.html, meth)(context)
  File "~/anaconda3/envs/jyyslide-md/lib/python3.10/site-packages/lxml/html/__init__.py", line 873, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "~/anaconda3/envs/jyyslide-md/lib/python3.10/site-packages/lxml/html/__init__.py", line 761, in document_fromstring
    raise etree.ParserError(
lxml.etree.ParserError: Document is empty

```

简易的临时修复，提供一个思路，但中文挂了：
<img width="602" alt="image" src="https://github.com/zweix123/jyyslide-md/assets/46419702/e707debd-d7f3-4a5a-bd58-c6bfdc2d92fe">

**Comment by zweix123** [comment]
我确实没有mac环境做测试。

**Comment by yurhett** [comment]
> 我确实没有mac环境做测试。

如果需要协助，我愿意提供环境以供完善。

**Comment by zweix123** [comment]
该问题似乎是由于依赖库的版本不正确，目前已更新相关依赖库，请使用Poetry管理依赖尝试重新运行。

```bash
poetry install  # 下载依赖
poetry shell    # 进入虚拟环境
python ...        # 运行
```

>很抱歉间隔这么长时间回复

**Comment by yurhett** [comment]
感谢 我有空测试一下后回复

**Comment by zweix123** [comment]
我得到了MacOS环境，测试并未出现问题，我的环境如下

<img width="443" alt="image" src="https://github.com/zweix123/jyyslide-md/assets/74446314/7ddc5647-f610-49cc-9f41-f19e7bd92b60">
